[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
  "cp .env.example .env",         # ضروري لإنشاء ملف .env أولاً
  "php artisan key:generate",
  "composer install",
  "php artisan migrate --force",
  "npm ci",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
