services:
  - type: web
    name: Ecommerce_back-end
    plan: free
    region: frankfurt
    branch: master
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
        value: base64:q94R9ImidYxd2we5hYDs9bt8eZKB5pYXhWq6TqG0Dx4=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://Ecommerce_back-end.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d14056e3jp1c73dh1f0g-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ecommerce_back_end_oxse
      - key: DB_USERNAME
        value: ecommerce_back_end_oxse_user
      - key: DB_PASSWORD
        value: WOTTmVCB6lWAtOUaaRhTViVfc3vsm5hB
