services:
  - type: web
    name: Ecommerce_back-end
    plan: free
    region: frankfurt
    branch: master
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:dbc4Iv8qXqtz3fasieA+W7bY+9/Acv3BSWNOi6UAUMg=
      - key: APP_DEBUG
        value: "false"
      - key: APP_STORAGE
        value: /var/www/html/storage
      - key: APP_URL
        value: https://ecommerce-back-end.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d14056e3jp1c73dh1f0g-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ecommerce_back_end_oxse
      - key: DB_USERNAME
        value: ecommerce_back_end_oxse_user
      - key: DB_PASSWORD
        value: WOTTmVCB6lWAtOUaaRhTViVfc3vsm5hB
      - key: DB_SSLMODE
        value: require
      # إعدادات الجلسات والتخزين المؤقت
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      # مفاتيح Passport
      - key: PASSPORT_PRIVATE_KEY
        value: |
          -----BEGIN PRIVATE KEY-----
          MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCR4qr1SAv0ANlm
          WzNxcoIrTi05FuG2P4wHjL9kCpgX0SvcFxKioSrX0lcg1ATrn6ixvZkmvyb5QQMC
          cVj9qW8Ts8b9dvX+PwvZGNH1f3zxsTRVIegyF9yFgBhVWAn5u15Cg1XWW8CV26QG
          xEnX6o01itoGvxjJFlCnx+doBGZh5BA+2H7O3ySwWVt8ahwYqsdiT2aHmPP23ld4
          txp60G2UvAXbvWWnjo/1HdSvQjoA9SZlJMKIe4Ad2nMNlpQcM4bhFvbIJNRzkvBB
          666rZkYciJnmKR1fkN8rGdpr5OLQPKfzDS/w/sPp3oj5hX5D46MShXhM49TQNUej
          7NTQ1Bc3zZf9vn0CdZ8jdZIBA3yhGd2N9MGQlyuyrULa80GvBxwqz0d0UCZtuOOC
          qc+S8Xhrr/rRzmr7JOMJn0BwcBCuAjzhNRfy6LWPIHmAyK+s4P8kv1G/bbMKQE4X
          i8mfKKiQgBwue0stK3qMeZOdnDM0E0lOlNHxgWJpCRBeeeQcPklhCP517OGqG3Cc
          fsyFCjTQ85MmU9N3CUQQB+hfan+TQhk3Ujq8FfC2g89WRgxJTKPPGd7SwYAqWfia
          zV7sZ8CgGcu1x+HD2Rp0BL7yvT8w81FIwE/EtZkrDmLygiE7CaB57arZJtwz9dg6
          FNfTIrkHGrBHiwkT8SFEpILcDogpcwIDAQABAoICACp7tMdbJMf421Z4ZqG58/hC
          et7uL+rP1Kp6LV4ny6Tb8AbW3UFo574T7fWMaKZpR0oDaa8j6WiaqxKyCXVNOyCk
          sOUtGHPizkN5e+MfLjaAITpNdn3n/vsNk4h+6+DC1K9P6dZTv+CkJr8luE9daaPW
          /KkMS1571h8WEuhyp5IIRUbX6w25Y8jLLN4tVGNGkGurrbL9MsaIdzabM+Xh/pda
          reYQ4KKL3JZICqDDC3st6PF5ZAE03dlTvT+OwzD3PGceNd2RBCFn//lidepKDU7P
          5OlmvbwPxz2Y+MeEzxxPHaWlCHoI5uqbOI5Zdqy0hM+m+KKDknzTlzpAhLUPnnbc
          EZcxvrO6kAoLBR5yOPEKgEkPcj9/DnKDK2BzTKjnJEWnjOKTLyG47BVMawylEoKE
          +Bt3hkboObmgR8hyHcUhuQd5S1ILDrF66tbT3I7pJ+vfpr5Xl6rUW6wzis/9olQ0
          cn/oB86M6lUWH7urozSHR06D1iaWR4eGVd5MO5zdE1ylpVfpn2lCdPVCdBRhyBMY
          /HoHSxDBp4W8pc5ToJABPU97BAE3bwZmRAImmNjFYF8GbGfB76p+Tf3u6OGf/hiK
          PLs2ZQJvBTO21M9bOoR83rTTR6QnUkHHmBHkPZYC4Ucc8psnjso6JwJvm/bRzxj5
          vVuZNJCIqlvsz9BO3U7ZAoIBAQDIeqrnRw0QzYgZIpmDo3EjnXQBUjpo7m/5jKQD
          iljzx6aFNcVk7VBwzsFwzKI/vCSxFuBpVccNLLsMIgTQRC6PoCml2EdoeycU+Wwl
          TXH1OCxN289fu4OMpoIjQZAsql19FqjlmVCN2eN6f8tKoT851syP/UYhg9XUoDt1
          bCjoLen3nXJknvDyQtfAo5sX81OQ2Cqd8wN+qb6JWB0RtVYlXzwYBHL+lGPI4wOD
          DPfvYa2IYOjYg7toR2YzGiCe69lR4CJ8u0wNcQQ9pCM84c1cWv+mTPYMlCj+qV/o
          WgY/gqw5VoWWHnCViobeY1asZCU4rnS6NjPQK54L0YgSgo+HAoIBAQC6SXpW5Z4i
          YkrFWtJLZU2WN673j+tSvRlCRhhDfxp3wYhNak5FuqbI0JHyOQzVpEyVLqa50gkR
          d184ki8hQFXDyiISvuhTq+RvZq20p8ULow/J6mU0gRdXUlGc26ioqbVsLOLep9V/
          Lht52u/Zv1iZtS03N4yjU0NhwfA0gQ6fu1+NuU78EemZcsWz/NolmOUZcZw4udUr
          fwC6djJdhslJq+aXwKT7grcgrH7Ut4Jts5r93lsJVYxOmivHGYeeLe4XikeqYmcO
          DRBFnZCGETrfvfcyqLcXyMChqu6MGmvYrgcIDERMZjp6G7Z6M77701lw7OTE4iTN
          vhjI56pOR5m1AoIBAGTWbogOEOBWwRIDeTvhRdMoK2VOutp0tBXNS+IMAFn+Hh/6
          v+LYCxHyrRHTm/h65em9G/tfjdNuoFal9c3bvZ+4a7pjYueGqk2+d0r7/Unei0pO
          6wT5fTAdtu/KWwRc+7drQ2RXC3b2YkQq8dQqZb4+fLeH5V9vvBEbPnT4XO0nMGXc
          eMIO4IC/CQTDK41EC/dGyZH7k3FfW0a1/JNu8CB4FQbMxyXkkAonn3n7bhEb5Qyi
          HGc5wF83YkcRqFLlvGMaPNQ81yrqBYDkT5Ef4pkCggEAFSmFuVtqZHOQFO1lWGVQ
          tBDtUnhJ/mM2/F1kIj7NLe+RYWIDNE6o5cUz3zV17Ms2W/gpvpBKsW5DJfUNX5Sk
          aZKL3l9Lmz26vKEIeK5aZyEGCSUUjCtiEGxskwotFcP5tSlAOJUOXt1JB8XEW5Mu
          KH/5e/1Wf7NUw0U52W0T0TeC+mGjxGTwiZsNNI4z5fOBiytp2NPbkI5j8cq9m/xU
          34aksnaTB3NpBFA0NEwIiBfQMqjQ5LWQM9m1wW94BZMoKgpua7+z/1eikpX8tg49
          Bu/YpiueaRhIMdVuNgJGYB4c9GAYXil62SZOy4EXYBo5Xee7cVZTYgAHZsNSiIP/
          xQKCAQEAx627KcvGVS2VlhLWiQbZL6841JNNKy49ksWreSEcxrbqDMmlbraGtCd3
          uXYWJ3B+myMTS8UOYEZ3Jd917/dV2WLToBRUehPDMvkQJ6+SAK+05BEcyKo0svXt
          1Wfil3uC4SDgaiWMzihNOaSRseluEThMiRR33jyUHm6sooDMHkx0wkk0nZOXS3C0
          NdiI8sjtXmCubev7OEs+GwcoElwtIFSmVsk9PaOg5jvFv+1WaAEOPMZw8cKoJGrg
          qF3oZaUkVsf0ecOUGwQLN1YskXMbqKFiaf1HoBpcJytonOd4qyrTMB04tyVdQAyY
          eniug9gziDAtfPSYE81aWg/rCMAouA==
          -----END PRIVATE KEY-----
      - key: PASSPORT_PUBLIC_KEY
        value: |
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkeKq9UgL9ADZZlszcXKC
          K04tORbhtj+MB4y/ZAqYF9Er3BcSoqEq19JXINQE65+osb2ZJr8m+UEDAnFY/alv
          E7PG/Xb1/j8L2RjR9X988bE0VSHoMhfchYAYVVgJ+bteQoNV1lvAldukBsRJ1+qN
          NYraBr8YyRZQp8fnaARmYeQQPth+zt8ksFlbfGocGKrHYk9mh5jz9t5XeLcaetBt
          lLwF271lp46P9R3Ur0I6APUmZSTCiHuAHdpzDZaUHDOG4Rb2yCTUc5LwQeuuq2ZG
          HIiZ5ikdX5DfKxnaa+Ti0Dyn8w0v8P7D6d6I+YV+Q+OjEoV4TOPU0DVHo+zU0NQX
          N82X/b59AnWfI3WSAQN8oRndjfTBkJcrsq1C2vNBrwccKs9HdFAmbbjjgqnPkvF4
          a6/60c5q+yTjCZ9AcHAQrgI84TUX8ui1jyB5gMivrOD/JL9Rv22zCkBOF4vJnyio
          kIAcLntLLSt6jHmTnZwzNBNJTpTR8YFiaQkQXnnkHD5JYQj+dezhqhtwnH7MhQo0
          0POTJlPTdwlEEAfoX2p/k0IZN1I6vBXwtoPPVkYMSUyjzxne0sGAKln4ms1e7GfA
          oBnLtcfhw9kadAS+8r0/MPNRSMBPxLWZKw5i8oIhOwmgee2q2SbcM/XYOhTX0yK5
          BxqwR4sJE/EhRKSC3A6IKXMCAwEAAQ==
          -----END PUBLIC KEY-----